### ISSUE TITLE
`null` values in maps cause error

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/hiera#37]
global.yaml:

```yaml
mynull: null

mymap:
  mykey: null
```

>.\lookup.exe mynull
>null

>.\lookup.exe mymap
>Error: reflect: call of reflect.Value.Type on zero Value
