### ISSUE TITLE
--render-as json fails on empty map

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/hiera#45]
hiera.yaml
```yaml
version: 5
defaults:
  data_hash: yaml_data
  datadir: data
hierarchy:
  - name: global
    path: global.yaml
```

global.yaml
```yaml
empty_map: {}
```

```
lookup empty_map --render-as json
Error: json: unsupported type: map[interface {}]interface {}
```
