### ISSUE TITLE
plugindir broken on windows

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/hiera#64]
Trying out hiera 0.3 and getting an error with plugins

```
version: 5
defaults:
  plugindir: C:\Temp\hiera\plugins
hierarchy:
  - name: one
    data_hash: terraform_backend
    options:
      backend: local
      config:
        path: C:\Temp\hiera\one.tfstate
```

```
lookup.exe test
Error: unable to start plugin /C:/Temp/hiera/plugins/terraform_backend.exe: exec: "/C:/Temp/hiera/plugins/terraform_backend.exe": file does not exist
```

Looks like `(dgo.Loader).AbsoluteName()` is returning the path with `/` prefixed
