### ISSUE TITLE
lookup function panics on non-existing key

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/hiera#69]
hiera.yaml
```yaml
version: 5
hierarchy:
  - name: yaml
    path: yaml1.yaml
```

yaml1.yaml
```yaml
yaml1: "%{lookup('nothing')}"
```

```
> lookup yaml1
Error: runtime error: invalid memory address or nil pointer dereference
```

Previously this used to return `undef`
