### ISSUE TITLE
lookup_key options should support interpolation

### ISSUE THREAD

**Issue by raffraffraff** [lyraproj/hiera#96]
I created a an [AWS SSM Parameter Store plugin](https://github.com/raffraffraff/hiera_aws_ssm_parameter_store). It works, so I can write secrets to the parameter store and reference them from Hiera. An example `hiera.yaml` configuration that uses the plugin looks like this:

```
---
version: 5

defaults:
  plugindir: ./plugins
  datadir: ./data
  data_hash: yaml_data

hierarchy:
  - name: region
    path: region/%{region}.yaml

  - name: environment
    path: environment/%{environment}.yaml

  - name: common
    glob: defaults/*.yaml

  - name: secrets
    lookup_key: "aws_ssm_parameter"
    options:
      aws_profile_name: production.AdministratorAccess
      aws_region: "us-west-1"
```

What I had hoped to do was to use interpolation of `%{environment}` and `%{region}` in the _options_ section, like this:

```
  - name: secrets
    lookup_key: "aws_ssm_parameter"
    options:
      aws_profile_name: "%{environment}.AdministratorAccess"
      aws_region: "%{region}"
```

This would enable Hiera to seamlessly switch between AWS accounts and regions based on these "facts" (or in the case of the Terraform Hiera provider, based on provider scope). Unfortunately, interpolation doesn't work for options so I must hard-code them. This forces me to store all parameters within a single AWS account and region.
